In [1]:
import numpy as np

In [2]:
import arrayfire as af

In [3]:
bins = np.zeros(5,dtype=np.int32)
pos = [1,0,2,0,3]
wts = [1,2,1,1,4]
a,b = np.histogram(pos,bins=5,range=(0,5),weights=wts)

In [42]:
af_bins = af.data.constant(0, 5, dtype=af.Dtype.f64)
af_pos = af.Array([1,0,2,0,3])
af_wts = af.Array([1,2,1,1,4])
af_a = af.histogram(af_pos, 6, -1, 5)

In [5]:
a = af.data.constant(0,5)
a

arrayfire.Array()
Type: float
[5 1 1 1]
    0.0000 
    0.0000 
    0.0000 
    0.0000 
    0.0000 


In [50]:
x = af.Array([-0.5, 0, 0.5, 1.0, 1.5])
af_pos = af.Array([1,0,2,0,3])
af_wts = af.Array([1,2,1,1,4])
af_a = np.histogram(af_pos, bins = x.elements(), range = (0, x.elements()), weights=af_wts)

In [51]:
af_a

(array([ 3.,  1.,  1.,  4.,  0.], dtype=float32),
 array([ 0.,  1.,  2.,  3.,  4.,  5.]))